### ISSUE TITLE
1 Issue 1 Suggestion

### ISSUE THREAD

**Issue by mahmutelmas06** [db0x/bigavatar-db0x.de#1]
1 Issue - Icon should be displayed top of the panel. My sound and (soft brightness extension) brightness settings seems top of picture sometimes. Some times it is on top. Strange

2- Open profile settings when clicked on the picture

by the way i use Dash to Panel extension.

**Comment by db0x** [comment]
1 - I have to refactor the extension because it is not compatible to gnome 3.36 (Ubuntu 20.04) .. If I find the time to do this, I will try to fix this.

2 - is on the list :)

**Comment by db0x** [comment]
I cannot reproduce the problem of what you describe. Maybe it's because of "dash2panel" I don't use this.

Your wish to open the accounts with a click has been implemented https://github.com/db0x/bigavatar-db0x.de/commit/7e3d366528589cd8f7109c8d63a981d3fa07b3a7
