### ISSUE TITLE
Add user's name below the image

### ISSUE THREAD

**Issue by mansoormemon** [db0x/bigavatar-db0x.de#2]
Can you add user's name and separator below the image.

**Comment by db0x** [comment]
Nice idea .. I'll try it ..

**Comment by mansoormemon** [comment]
Any updates.

**Comment by db0x** [comment]
not time yet for this project :( but it will be done later

**Comment by db0x** [comment]
it is solved in this fork https://github.com/GustavoPeredo/Big-Avatar-Gnome-Shell-Extension
